
server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          default-label: main
          uri: ${CLOUD_CONFIG_SERVER_URI}
          search-paths: 
            - transaction